---
title: "Descriptive statistics"
author: "Gustavo Ahumada"
date: "2023-03-06"
header-includes:
   - \usepackage{float}
output:
  pdf_document:
  keep_tex: yes
  latex_engine: pdflatex
---

```{r setup, include=FALSE}
# set working directory
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir='/Volumes/GoogleDrive/My Drive/Reserach_in_progress/social_turst_membership/sem_trabajo/data')
```

```{r cargar-paquetes-4, include = FALSE}
# libraries
rm(list=ls())
library(knitr)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(survey)
# devtools::install_github('edgardo-cerda/elsoc')
library(elsoc)
# library(lubridate)
library(viridis)
library(statar)
library(expss)
library(ggstats)
library(ggpubr)
library(vtable)
```

```{r}
# load dataset
load('ELSOC_Long.RData')
elsoc_long_2016_2022[elsoc_long_2016_2022 == "-999"] <- NA
elsoc_long_2016_2022[elsoc_long_2016_2022 == "-888"] <- NA

#val_lab(data$c12_01)

# include age as a factor variable
elsoc_long_2016_2022$edad2 <- cut(elsoc_long_2016_2022$m0_edad, 
                      breaks = c(18, 30, 60, 92),
                      labels = c("Young", "Adult", "Old"))

# save output
save_output <- "/Volumes/GoogleDrive/My Drive/Reserach_in_progress/social_turst_membership/sem_trabajo/output/new_output/"
```

```{r, fig.cap = 'Junta de vecinos u otra organizacion vecinal, según sexo'}
elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>%
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(c12_01 %in% 3, by = c(ola, m0_sexo), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = m0_sexo, color = factor(m0_sexo),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Men", "Woman"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Active member of the neighborhood council or other neighborhood organization") +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 
ggsave(path = save_output, filename = "fig1.png")
```

```{r, fig.cap = 'Junta de vecinos u otra organizacion vecinal, según edad'}
elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(c12_01 %in% 3, by = c(ola, edad2), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = edad2, color = factor(edad2),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Young", "Adult", "Old"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Active member of the neighborhood council or other neighborhood organization") +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 
ggsave(path = save_output, filename = "fig2.png")
```

```{r, fig.cap = 'Organizaciones religiosas, según sexo'}
elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(c12_02 %in% 3, by = c(ola, m0_sexo), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = m0_sexo, color = factor(m0_sexo),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Men", "Woman"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Active Member Religious Organizations") +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 
ggsave(path = save_output, filename = "fig3.png")

```

```{r, fig.cap = 'Organizaciones religiosas, según edad'}
elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(c12_02 %in% 3, by = c(ola, edad2), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = edad2, color = factor(edad2),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Young", "Adult", "Old"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Active Member Religious Organizations") +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 
ggsave(path = save_output, filename = "fig4.png")
```

```{r, fig.cap = 'Organizacion deportiva, según sexo'}
elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(c12_07 %in% 3, by = c(ola, m0_sexo), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = m0_sexo, color = factor(m0_sexo),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Men", "Woman"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Active member Sports organization") +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 
ggsave(path = save_output, filename = "fig5.png")
```

```{r, fig.cap = 'Organizacion deportiva, según edad'}
elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>%
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(c12_07 %in% 3, by = c(ola, edad2), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = edad2, color = factor(edad2),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Young", "Adult", "Old"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Active member Sports organization") +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 
ggsave(path = save_output, filename = "fig6.png")

```

```{r, fig.cap = 'Social trust'}
plot1 <- elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(c02 %in% 1, by = c(ola, m0_sexo), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = m0_sexo, color = factor(m0_sexo),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Men", "Woman"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 1))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Social trust") 


plot2 <- elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>%
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(c02 %in% 1, by = c(ola, edad2), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = edad2, color = factor(edad2),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Young", "Adult", "Old"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 1))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '') +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 

figure <- ggarrange(plot1, plot2,
                    ncol = 1, nrow = 2)
ggsave(path = save_output, filename = "fig7.png")

```

```{r}
# create dummy vaeriable for membership
elsoc_long_2016_2022 = elsoc_long_2016_2022 %>%
  dplyr::mutate(cc12_01 = ifelse(c12_01 > 2, 1, 0)) %>% 
  dplyr::mutate(cc12_02 = ifelse(c12_02 > 2, 1, 0)) %>% 
  dplyr::mutate(cc12_03 = ifelse(c12_03 > 2, 1, 0)) %>% 
  dplyr::mutate(cc12_04 = ifelse(c12_04 > 2, 1, 0)) %>% 
  dplyr::mutate(cc12_05 = ifelse(c12_05 > 2, 1, 0)) %>% 
  dplyr::mutate(cc12_06 = ifelse(c12_06 > 2, 1, 0)) %>% 
  dplyr::mutate(cc12_07 = ifelse(c12_07 > 2, 1, 0)) %>% 
  dplyr::mutate(cc12_08 = ifelse(c12_08 > 2, 1, 0))

# multiple membership
elsoc_long_2016_2022 <- elsoc_long_2016_2022 %>% 
  mutate(sum_memb = rowSums(select(., "cc12_01", "cc12_02", "cc12_03", "cc12_04",
                                  "cc12_05", "cc12_06", "cc12_07", "cc12_08")))
```

```{r}
## bar plot of number of membership 
# 2016
p2016 <- elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% 1) %>% 
  ggplot() +
  geom_bar(mapping = aes(x = sum_memb, y = after_stat(prop)), stat = "count") +
  coord_flip() + 
  ylab("Proportion") +
  xlab("Membership") +
  theme_bw() +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Multiple membership, 2016")

# 2018
p2018 <- elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>%
  filter(ola %in% 3) %>% 
  ggplot() +
  geom_bar(mapping = aes(x = sum_memb, y = after_stat(prop)), stat = "count") +
  coord_flip() + 
  ylab("Proportion") +
  xlab("Membership") +
  theme_bw() +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Multiple membership, 2018") 

# 2022
p2022 <- elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>%
  filter(ola %in% 6) %>% 
  ggplot() +
  geom_bar(mapping = aes(x = sum_memb, y = after_stat(prop)), stat = "count") +
  coord_flip() + 
  ylab("Proportion") +
  xlab("Membership") +
  theme_bw() +
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '',
          subtitle = "Multiple membership, 2022") +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 

figure <- ggarrange(p2016, p2018, p2022,
                    ncol = 1, nrow = 3)
ggsave(path = save_output, filename = "fig8.png")
```

```{r, fig.cap = 'member of one or two organizations, by sex'}
plot1 <- elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>%
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(sum_memb %in% 2:8, by = c(ola, m0_sexo), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = m0_sexo, color = factor(m0_sexo),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Man", "Woman"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.8))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '') 
```

```{r}
plot2 <- elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>%
  filter(ola %in% c(1, 3, 6)) %>% 
  sjlabelled::as_label(ola) %>%
  prop_list(sum_memb %in% 2:8, by = c(ola, edad2), na.rm = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(x = ola, y = prop, group = edad2, color = factor(edad2),
             label = scales::percent(prop, accuracy = .1)))+
  geom_point()+
  geom_line() +
  geom_text_repel(nudge_y = .01, size = 3, color = 'black') +
  theme_bw()+
  ylab(label = NULL) +
  xlab(label = NULL) +
  scale_color_viridis_d(begin = 0, end = .8, option = 'viridis',
                        labels = c("Young", "Adult", "Old"))+
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.8))+
  theme(plot.caption = element_text(hjust = 0),
        legend.position = 'top',
        legend.title = element_blank())+
  ggtitle(label = '') +
  labs(caption = "Source: Own preparation based on ELSOC 2016-2022.") 

figure2 <- ggarrange(plot1, plot2,
                    ncol = 1, nrow = 2)
ggsave(path = save_output, filename = "fig9.png")

```

```{r}
# recode variables
elsoc_long_2016_2022 = elsoc_long_2016_2022 %>%
  dplyr::mutate(m0_sexo2 = ifelse(m0_sexo > 1, 1, 0)) %>% # female
  dplyr::mutate(m012 = ifelse(m01 > 4, 1,0)) %>%
  dplyr::mutate(trust = ifelse(c02 == 1, 1, 0))
   

# filter dataset
data <- elsoc_long_2016_2022 %>%
  filter(muestra == 1) %>% 
  filter(tipo_atricion == 1) %>% 
  filter(ola %in% c(1, 3, 6)) 

dataset = subset(data, select = c(ola, m0_edad, m0_sexo2, m012, trust,cc12_01, cc12_02,
                                  cc12_03,cc12_04,cc12_05, cc12_06, cc12_07,
                                  cc12_08, sum_memb))
val_lab(elsoc_long_2016_2022$c02)
# descriptive statistics
sumtable(dataset)

# labels
labs <- c("Age","Female", "Secondary edu. >", "Social trust",
          "Neighborhood org.", "Religious org.", "Political party",
          "Union", "Profesional org.", "Charitable org.",
          "Sports org.", "Student org.", "Multiple memberships")
# table1. descriptive statistics
st(dataset, group = 'ola', group.test = FALSE,
   labels = labs, out = 'latex', file = "table1.tex")
```

```{r}
# descriptive function
myDescriptives = function(x) {
    x = as.numeric(x)
    m = mean(x, na.rm = TRUE)
    md = median(x, na.rm = TRUE)
    sd = sd(x, na.rm = TRUE)
    return(c(m, md, sd))
}
myDescriptives(c(data$m0_sexo2, data$m0_sexo))



table(elsoc_long_2016_2022$cc12_01)
fre(elsoc_long_2016_2022$m0_sexo)
val_lab(elsoc_long_2016_2022$m0_sexo)
```
